<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuperheroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('superheroes')->insert([
            [
                'real_name' => 'Tony Stark',
                'pseudo_name' => 'Iron Man',
                'gender' => 'Male',
                'origin_planet' => 'Earth',
                'description' => 'Genius billionaire and philanthropist.',
                'superpowers' => json_encode(['Intelligence', 'Engineering']),
                'city_of_protection' => 'New York',
                'gadgets' => json_encode(['Iron Man Suit']),
                'team' => 'Avengers',
                'vehicle' => 'Audi R8',
                'user_id' => 1,
            ],
            [
                'real_name' => 'Bruce Wayne',
                'pseudo_name' => 'Batman',
                'gender' => 'Male',
                'origin_planet' => null,
                'description' => 'The Dark Knight of Gotham.',
                'superpowers' => json_encode(['Martial Arts', 'Detective Skills']),
                'city_of_protection' => 'Gotham',
                'gadgets' => json_encode(['Batarang', 'Grappling Gun']),
                'team' => null,
                'vehicle' => 'Batmobile',
                'user_id' => 2,
            ],
            [
                'real_name' => 'Clark Kent',
                'pseudo_name' => 'Superman',
                'gender' => 'Male',
                'origin_planet' => 'Krypton',
                'description' => 'The Man of Steel, protector of Earth.',
                'superpowers' => json_encode(['Super Strenth', 'Flight', 'Heat Vision']),
                'city_of_protection' => 'Metropolis',
                'gadgets' => json_encode([]),
                'team' => 'Justice League',
                'vehicle' => null,
                'user_id' => 3,
            ],
            [
                'real_name' => 'Diana Prince',
                'pseudo_name' => 'Wonder Woman',
                'gender' => 'Female',
                'origin_planet' => 'Themyscira',
                'description' => 'Amazonian warrior and ambassador of peace.',
                'superpowers' => json_encode(['Super Strength', 'Lasso of Truth', 'Combat Skills']),
                'city_of_protection' => 'Washington DC',
                'gadgets' => json_encode(['Lasso of Truth', 'Bracelets of Submission']),
                'team' => 'Justice League',
                'vehicle' => 'Invisible Jet',
                'user_id' => 4,
            ],
            [
                'real_name' => 'Peter Parker',
                'pseudo_name' => 'Spider-Man',
                'gender' => 'Male',
                'origin_planet' => 'Earth',
                'description' => 'Friendly neighborhood superhero.',
                'superpowers' => json_encode(['Wall-Crawling', 'Spider-Sense', 'Super Strength']),
                'city_of_protection' => 'New York City',
                'gadgets' => json_encode(['Web-Shooters']),
                'team' => 'Avengers',
                'vehicle' => null,
                'user_id' => 5,
            ],
            [
                'real_name' => 'Natasha Romanoff',
                'pseudo_name' => 'Black Widow',
                'gender' => 'Female',
                'origin_planet' => 'Earth',
                'description' => 'Master spy and assassin.',
                'superpowers' => json_encode(['Martial Arts', 'Espionage']),
                'city_of_protection' => 'New York City',
                'gadgets' => json_encode(['Widow s Bite', 'Grappling Hook']),
                'team' => 'Avengers',
                'vehicle' => null,
                'user_id' => 6,
            ],
            [
                'real_name' => 'Barry Allen',
                'pseudo_name' => 'Flash',
                'gender' => 'Male',
                'origin_planet' => 'Earth',
                'description' => 'The fastest man alive.',
                'superpowers' => json_encode(['Super Speed', 'Time Travel']),
                'city_of_protection' => 'Central City',
                'gadgets' => json_encode([]),
                'team' => 'Justice League',
                'vehicle' => null,
                'user_id' => 7,
            ],
            [
                'real_name' => 'Steve Rogers',
                'pseudo_name' => 'Captain America',
                'gender' => 'Male',
                'origin_planet' => 'Earth',
                'description' => 'Super-soldier and symbol of freedom.',
                'superpowers' => json_encode(['Super Strength', 'Enhanced Agility', 'Shield Mastery']),
                'city_of_protection' => 'New York City',
                'gadgets' => json_encode(['Vibranium Shield']),
                'team' => 'Avecngers',
                'vehicle' => null,
                'user_id' => 8,
            ],
            [
                'real_name' => 'Thor Odinson',
                'pseudo_name' => 'Thor',
                'gender' => 'Male',
                'origin_planet' => 'Asgard',
                'description' => 'God of Thunder with a mighty hammer.',
                'superpowers' => json_encode(['Super Strength', 'Flight', 'Weather Manipulation']),
                'city_of_protection' => 'Asgard and Earth',
                'gadgets' => json_encode(['Mjolnir']),
                'team' => 'Avengers',
                'vehicle' => null,
                'user_id' => 9,
            ],
            [
                'real_name' => 'Hal Jordan',
                'pseudo_name' => 'Green Lantern',
                'gender' => 'Male',
                'origin_planet' => 'Earth',
                'description' => ' Intergalactic peacekeeper with a power ring.',
                'superpowers' => json_encode(['Energy Constructs', 'Flight', 'Force Fields']),
                'city_of_protection' => 'Coast City',
                'gadgets' => json_encode(['Power Ring']),
                'team' => 'Justice League',
                'vehicle' => null,
                'user_id' => 10,
            ],
        ]);
    }
}
